#!/bin/bash

# doclib_dummy_file_creator.sh
# This script reads a filelist.txt (generated by 'find -type f > filelist.txt')
# and recreates the directory structure and dummy files found within a customer's document library.

FILELIST="filelist.txt"

# Check if the filelist.txt exists
if [ ! -f "$FILELIST" ]; then
    echo "Error: $FILELIST not found."
    echo "Please create it first using: find -type f > $FILELIST"
    exit 1
fi

echo "Reading file paths from $FILELIST..."

# Read the filelist line by line
while IFS= read -r filepath; do
    # Skip empty lines
    if [ -z "$filepath" ]; then
        continue
    fi

    # Extract the directory path from the full file path
    # dirname command gets the directory name of a file path
    dirpath=$(dirname "$filepath")

    # Create the directory if it doesn't exist
    # -p option creates parent directories as needed and doesn't complain if directory exists
    if [ ! -d "$dirpath" ]; then
        echo "Creating directory: $dirpath"
        mkdir -p "$dirpath"
    fi

    # Create the dummy file
    # touch command creates an empty file if it doesn't exist, or updates its timestamp if it does
    echo "Creating dummy file: $filepath"
    touch "$filepath"

done < "$FILELIST"

echo "DocLib Dummy file structure creation complete."